### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [42]:
import numpy as np
N = 10
np.linspace(N-1, 0, N)

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

In [46]:
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [52]:
matrix = np.diag(np.arange(N-1, -1, -1), k=0)
matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
sum(np.diagonal(matrix, offset=0, axis1=0, axis2=1)) # offset=0, axis1=0, axis2=1 это значения заданные по умолчанию для центральной диагонали

45

In [62]:
sum(np.diagonal(matrix))

45

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12 

5y + 4z = -3



In [65]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.

На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [7]:
import numpy as np
from numpy import linalg
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [134]:
better = dict()
lenght_nus = np.linalg.norm(next_user_stats)
for i, el in enumerate(users_stats):
    length_el = np.linalg.norm(el)
    cosinus = np.dot(el, next_user_stats) / (length_el * lenght_nus)
    better[i+1] = cosinus
BIG = max(better.values())
for key, value in better.items():
    if value == BIG:
        BKey = key

print(f'Покупатель с user_id №: {BKey}, со значением {round(BIG, 2)} подходит лучше всего по интересам к новому покупателю')

Покупатель с user_id №: 8, со значением 0.95 подходит лучше всего по интересам к новому покупателю


In [174]:
lenght_nus = np.linalg.norm(next_user_stats)
a = np.full(10, 0)
for i, el in enumerate(users_stats):
    length_el = np.linalg.norm(el)
    cosinus = np.dot(el, next_user_stats) / (length_el * lenght_nus)
    np.add(cosinus, a)
    
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])